site_name: Riotee
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'index.md'
  - 'basics.md'
  - 'quickstart.md'
  - 'Hardware':
    - 'Module': 'hardware/module.md'
    - 'Board': 'hardware/board.md'
    - 'Solar Shield': 'hardware/solar_shield.md'
    - 'Capacitor Shield': 'hardware/capacitor_shield.md'
    - 'Sensor Shield': 'hardware/sensor_shield.md'
    - 'Probe': 'hardware/probe.md'
  - 'Software':
    - 'Runtime': 'software/runtime.md'
    - 'Drivers':
      - 'GPIO': 'software/drivers/gpio.md'
      - 'ADC': 'software/drivers/adc.md'
      - 'UART': 'software/drivers/uart.md'
    - 'Examples':
      - 'ADC': 'software/examples/adc.md'
      - 'Blinky': 'software/examples/blinky.md'
  - 'Networking':
    - 'Stella': 'networking/stella.md'
    - 'BLE': 'networking/ble.md'
  - 'miscellaneous.md'
  - 'legal_notice.md'

markdown_extensions:
  - pymdownx.snippets:
      base_path:
      - "."
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - mkdoxy:
      projects:
        riotee:
          src-dirs: core/include examples
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "riotee_*.h* main.c"
            RECURSIVE: True
            EXAMPLE_PATH: ""