name: Deploy docs

on:
  push:

jobs:
  call-build-docs:
    uses: ./.github/workflows/build-docs.yml
  deploy-docs:
    runs-on: ubuntu-latest
    needs: call-build-docs
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: docs_html

    - name: Deploy docs on webserver
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: www.riotee.nessie-circuits.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/riotee/docs/latest/
        protocol: ftps