name: Release Arduino package

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  call-test-arduino:
    uses: ./.github/workflows/test-arduino.yml
  release-arduino:
    runs-on: ubuntu-latest
    name: Release core package to webserver
    needs: call-test-arduino
    steps:
      - name: Install dependencies of envsubst
        run: sudo apt update && sudo apt install gettext-base

      - uses: actions/checkout@v3

      - run: mkdir output

      - uses: actions/download-artifact@v3
        with:
          name: core_zip
          path: output/Riotee_ArduinoCore_${{github.ref_name}}.zip

      - uses: actions/download-artifact@v3
        with:
          name: zip_props

      - name: Load zip properties into environment variables
        run: cat zip_props.env >> $GITHUB_ENV

      - name: Store release tag in environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
  
      - name: Render template of package_index snippet for release
        run: envsubst < arduino/package_index_snippet.tmpl > output/package_index_snippet.json

      - name: Upload package index snippet as artifact
        uses: actions/upload-artifact@v3
        with:
          name: package_index_snippet
          path: output/package_index_snippet.json

      - run: ls -lha output
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/Riotee_ArduinoCore_${{github.ref_name}}.zip